### ISSUE TITLE
ListEnterpriseStreams method of AdminClient doesn't set the values for isActive, isPublic, isExternal flags in AdminStreamInfo

### ISSUE THREAD

**Issue by VenkatJaladanki** [SymphonyPlatformSolutions/symphony-api-client-java#104]
When we call listEnterpriseStreams method on AdminClient, the list of AdminStreamInfo objects returning, but the values not setting for important flags (isActive, isPublic, isExternal) and always it's values are 'false'. But when we hit the actual end-point on Symphony we are getting these values as a result.

This is forcing us to call one more API call to get RoomInfo for the above flags.

Please fix this ASAP.

**Comment by symphony-thibault** [comment]
Hi @VenkatJaladanki, 

We are sincerely sorry for this very late answer 🙏 Do you still need support for this issue? 

Thibault

**Comment by symphony-thibault** [comment]
Closing this issue.
