### ISSUE TITLE
GETCONNECTIONS does not produce a valid URL

### ISSUE THREAD

**Issue by karlmoll** [SymphonyPlatformSolutions/symphony-api-client-java#13]
There should be a preceding '/' before the url definition in the following line:

https://github.com/SymphonyPlatformSolutions/symphony-api-client-java/blob/2906816f3d6a5649d9a67fb2664186726904099d/src/main/java/clients/symphony/api/constants/PodConstants.java#L26

The other url paths start with this on this page. The current result produces an invalid URL.

**Comment by mistryvinay** [comment]
The preceding URL has now been included within the PodConstants.java. Will close this issue.
