### ISSUE TITLE
SlashAnnotationProcessor triggers BeanCreationException when there are request scoped beans defined

### ISSUE THREAD

**Issue by putterson** [SymphonyPlatformSolutions/symphony-api-client-java#345]
We are running into an issue where on spring boot application startup the SlashAnnotationProcessor tries to create all the beans in our project, and some of them cannot be created out of their defined scope or cannot be created through applicationContext.getBean().
This issue affects all versions up to 1.5.0.BETA
When the exception is thrown it prevents our application from starting up.
I have a minimal repro of the issue at https://github.com/putterson/symphony-spring-bug-repro

**Comment by symphony-youri** [comment]
Thanks for reporting the issue @putterson and for the test project to reproduce the issue!
We are probably going to rework a bit the discovery of annotations to make sure beans are not created by mistake

**Comment by symphony-thibault** [comment]
Hi @putterson, 

This issue has resolved as part of [1.5.1.BETA](https://github.com/SymphonyPlatformSolutions/symphony-api-client-java/releases/tag/1.5.1.BETA) release. 

Please let us know if the issue is fixed on your side as well. 

Thanks!
