### ISSUE TITLE
Using the gradle-gradle-plugin to download all licenses

### ISSUE THREAD

**Issue by maoo** [SymphonyPlatformSolutions/symphony-api-client-java#416]
As part of [the FINOS Project Contribution](https://github.com/finos/community/issues/94), we need to validate all transitive licenses being distributed in the releases published in Maven Central.

I checked out this repo and added https://plugins.gradle.org/plugin/com.github.hierynomus.license-report to  `./build.gradle`:
```
buildscript {
    repositories {
        jcenter()
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath 'io.codearte.gradle.nexus:gradle-nexus-staging-plugin:0.22.0'
        classpath "gradle.plugin.com.hierynomus.gradle.plugins:license-gradle-plugin:0.15.0"
    }
}

apply plugin: 'io.codearte.nexus-staging'
apply plugin: "com.github.hierynomus.license-report"
```

When I run `gradle downloadLicenses` I see that `./build/license-dependency.html` is created (at root level), but not for all sub modules; could you help me understanding how to apply this command also for sub modules?

When this works, we could add a CircleCI task the continuously checks for suspicious or unknown licenses across all transitive dependencies.

Thanks in advance!

**Comment by symphony-thibault** [comment]
Hi @maoo, 

We did not managed to get the [license-report](https://plugins.gradle.org/plugin/com.github.hierynomus.license-report ) plugin working with our project. Instead, we used the [Gradle-License-Report](https://github.com/jk1/Gradle-License-Report) that works pretty well, and natively examines subprojects as well. Also, PR Builder integration was pretty simple with this plugin as we only had to run `gradle checkLicense` from CircleCI (example of report [here](https://1764-126734944-gh.circle-artifacts.com/0/~/reports/depedency-license/build/reports/dependency-license/index.html)).  

See PR https://github.com/SymphonyPlatformSolutions/symphony-api-client-java/pull/417

**Comment by maoo** [comment]
Great work, thanks @symphony-thibault . Closing issue.
