### ISSUE TITLE
Keep Alive strategy configuration for ApiClient

### ISSUE THREAD

**Issue by yinan-symphony** [SymphonyPlatformSolutions/symphony-api-client-java#441]
## Feature Request
As BDK ApiClient user, I'd like to be able to configure the keep alive strategy on the ApiClient.

### Description of Problem:
The current BDK ApiClient does not allow users to configure the KeepAlive strategy on the Jersey ApiClient implementation, such feature allows to have a better throughout in a high load situation.

...please resist the temptation to describe your request in terms of a solution.  Job Story form ("When [triggering condition], I want to [motivation/goal], so I can [outcome].") can help ensure you're expressing a problem statement.

### Potential Solutions:
...clearly and concisely describe what you want to happen. Add any considered drawbacks.

... if you've considered alternatives, clearly and concisely describe those too.

**Comment by symphony-youri** [comment]
@yinan-symphony is it something that needs to be exposed part of the BDK's configuration (YAML file) or it could be enough to have it as part of the Java API?

**Comment by yinan-symphony** [comment]
@symphony-youri yes, please make it configurable through the yaml file.

**Comment by symphony-thibault** [comment]
@yinan-symphony PR is ready https://github.com/SymphonyPlatformSolutions/symphony-api-client-java/pull/442 !
