### ISSUE TITLE
Provide base package

### ISSUE THREAD

**Issue by marcus-secato-symphony** [SymphonyPlatformSolutions/symphony-api-client-java#61]
Organize the existing packages under the same base package (e.g. org.symphony).
This is important for troubleshooting applications using the Symphony API client as it would make easier for setting log level just for the Symphony API client.

**Comment by ystan-** [comment]
As this is a breaking change, it has been prioritised as part of the next major version (2.0) series of this sdk where there are other broader (and breaking) changes.

**Comment by symphony-thibault** [comment]
Fixed with BDK2.0, root package is `com.symphony.bdk.core`
