### ISSUE TITLE
No message body reader has been found for class model.Token

### ISSUE THREAD

**Issue by ermadan** [SymphonyPlatformSolutions/symphony-api-client-java#70]
Looks like missing dependency problem, but i have the symphony-api-client-java:1.0.37 in the pom

```
Aug 16, 2019 4:29:11 AM org.apache.cxf.jaxrs.utils.JAXRSUtils logMessageHandlerProblem
SEVERE: No message body reader has been found for class model.Token, ContentType: application/json
Exception in thread "main" javax.ws.rs.client.ResponseProcessingException: No message body reader has been found for class model.Token, ContentType: application/json
	at org.apache.cxf.jaxrs.impl.ResponseImpl.reportMessageHandlerProblem(ResponseImpl.java:437)
	at org.apache.cxf.jaxrs.impl.ResponseImpl.doReadEntity(ResponseImpl.java:390)
	at org.apache.cxf.jaxrs.impl.ResponseImpl.readEntity(ResponseImpl.java:314)
	at org.apache.cxf.jaxrs.impl.ResponseImpl.readEntity(ResponseImpl.java:304)
	at authentication.SymBotAuth.sessionAuthenticate(SymBotAuth.java:120)
	at authentication.SymBotAuth.authenticate(SymBotAuth.java:75)

```

**Comment by ystan-** [comment]
is this run after building a JAR? if you're using maven, please try using the maven shade plugin and adding the services resources transformer in your pom.xml. a sample can be found here: https://github.com/SymphonyPlatformSolutions/symphony-decision-tree-bot/blob/master/pom.xml#L60

**Comment by ermadan** [comment]
No, i'm running from intellij. Do you understand what is missing from the trace?

**Comment by ystan-** [comment]
can you post your pom.xml please?

**Comment by ermadan** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.db.kyc</groupId>
    <artifactId>nlp-probe</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <java.version>1.8</java.version>
        <kotlin.version>1.3.21</kotlin.version>
        <ktor.version>1.2.2</ktor.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>${kotlin.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-test</artifactId>
            <version>${kotlin.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.oracle</groupId>
            <artifactId>ojdbc</artifactId>
            <version>11.2.0.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.nlpcraft</groupId>
            <artifactId>nlpcraft</artifactId>
            <version>0.7.0</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.exposed</groupId>
            <artifactId>exposed</artifactId>
            <version>0.13.3</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.4.0</version>
        </dependency>
        <dependency>
            <groupId>io.ktor</groupId>
            <artifactId>ktor-server-core</artifactId>
            <version>${ktor.version}</version>
        </dependency>
        <dependency>
            <groupId>io.ktor</groupId>
            <artifactId>ktor-client-apache</artifactId>
            <version>${ktor.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.ktor</groupId>
            <artifactId>ktor-client-json</artifactId>
            <version>${ktor.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.ktor</groupId>
            <artifactId>ktor-client-gson</artifactId>
            <version>${ktor.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.2</version>
        </dependency>
        <dependency>
            <groupId>com.symphony.platformsolutions</groupId>
            <artifactId>symphony-api-client-java</artifactId>
            <version>1.0.37</version>
            <exclusions>
            <exclusion>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-log4j12</artifactId>
            </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.inject</groupId>
            <artifactId>jersey-hk2</artifactId>
            <version>2.26</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.core</groupId>
            <artifactId>jersey-common</artifactId>
            <version>2.26</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jersey.connectors</groupId>
            <artifactId>jersey-apache-connector</artifactId>
            <version>2.19</version>
        </dependency>

        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpcore</artifactId>
            <version>4.4.10</version>
        </dependency>
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>4.5.6</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
        </dependency>

    </dependencies>

    
        
        
        
    

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.1</version>
            </plugin>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>${kotlin.version}</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <sourceDirs>
                                <source>src/main/java</source>
                                <source>src/main/kotlin</source>
                            </sourceDirs>
                        </configuration>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <jvmTarget>1.8</jvmTarget>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>testCompile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>2.6</version>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals> <goal>single</goal> </goals>
                        <configuration>
                            <archive>
                            <manifest>
                            <mainClass>org.nlpcraft.probe.NCProbe</mainClass>
                            </manifest>
                            </archive>
                            <descriptorRefs>
                                <descriptorRef>jar-with-dependencies</descriptorRef>
                            </descriptorRefs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>`

**Comment by ermadan** [comment]
`public class Test {
    public static void main(String[] argv) {
        SymConfig config = SymConfigLoader.loadConfig("src/main/resources/config.json");
        SymBotAuth botAuth =  new SymBotAuth(config);
        botAuth.authenticate();
    }
}
`

**Comment by ermadan** [comment]
and config - just in case
`{
  "_comment": "Mandatory section",
  "sessionAuthHost": "db-test-api.symphony.com",
  "sessionAuthPort": 443,
  "keyAuthHost": "ipsmpu02.de.db.com.symphony.com",
  "keyAuthPort": 8444,
  "podHost": "db-test.symphony.com",
  "podPort": 443,
  "agentHost": "ipsmpu01.de.db.com.symphony.com",
  "agentPort": 443,


  "_comment": "For bots only",
  "botUsername": "xxx",
  "botEmailAddress": "xxx",


  "_comment": "For bots using certificate authentication",
  "botCertPath": "src/main/resources/",
  "botCertName": "certificate.p12",
  "botCertPassword": "xxx",
  "proxyURL": "http://userproxy.intranet.db.com:8080",
  "proxyUsername": "",
  "proxyPassword": "",
  "truststorePath": "src/main/resources/server.truststore",
  "truststorePassword": "xxx"
}`

**Comment by ystan-** [comment]
[deleted your config comment as i don't recommend you posting internal addresses on a public website. your config looks correct, anyhow.]

can you try removing the jersey dependencies? if that still does not work, remove everything until you are left with only this dependency. in the recent releases of this sdk, you no longer need to add any other dependency to your project. jersey uses a service discovery mechanism to locate the message body reader and a conflicting dependency or loading it from a uber JAR can interfere with that (maven assembly seems to have issues as well).

**Comment by ermadan** [comment]
without other dependencies everything works fine, thank you very much!

**Comment by ystan-** [comment]
thanks for confirming. closing this issue now.
