### ISSUE TITLE
Symphony bot client thread safety

### ISSUE THREAD

**Issue by JosephP91** [SymphonyPlatformSolutions/symphony-api-client-java#76]
Hello everybody,

I was wondering if Symphony bot client class (SymBotClient) is thread safe. The question is:
can I send a message from different threads using the same istance of SymBotClient?

Thanks

**Comment by ystan-** [comment]
Hi @JosephP91 
Other than the initialisation and authentication portion, there are no data structures that are manipulated when using the SDK in general. Sending messages in particular, is quite a straightforward REST API binding so feel free to load these in an execution service of your choice. Do note that the real limitations are at the pod side, so exercise prudence in sizing your thread pool.
