### ISSUE TITLE
Question: if/how does this relate to the Java Client produced by the Symphony open source community?

### ISSUE THREAD

**Issue by pmonks** [SymphonyPlatformSolutions/symphony-api-client-java#8]
Keen to better understand if/how this project relates to the [Java Client recently produced by the Symphony open source community](https://github.com/symphonyoss/symphony-java-client).

**Comment by opoupeney** [comment]
There is no relation. The **symphony-api-client-java** repository refers to the Symphony supported and produced Java API client.

**Comment by pmonks** [comment]
@opoupeney functionally they appear to overlap quite substantially, which is rather confusing.

How should a developer choose between them?

**Comment by pmonks** [comment]
@opoupeney any updates on this?
