### ISSUE TITLE
lb-config.json is ignored

### ISSUE THREAD

**Issue by pobrien415** [SymphonyPlatformSolutions/symphony-api-client-java#81]
I have specified a lb-config.json and it says in the logs "Loading load balancer config from:/data/web/apps/jira/lb-config.json" but it still uses the agent specified in config.json

**Comment by ystan-** [comment]
- what version of the sdk are you using and do you have proxy configured in config.json? (there was a conflicting bug introduced with connectionTimeout and proxy configuration in 1.0.40 and fixed in 1.0.43)
- what are the contents of your lb-config.json?

**Comment by pobrien415** [comment]
sdk 1.0.47. no proxy. 

{
  "loadBalancing": {
    "method": "external",
    "stickySessions": true
  },
  "agentServers": [
    "sup-agent.symphony.com"
    
  ]
}

**Comment by ystan-** [comment]
do all the agent servers behind sup-agent have the additional flag in their startup.sh that reflects their actual hostnames?
`-Dhost.name=sym-agent-01.my-company.com`
